# Generated by Django 5.0 on 2023-12-07 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category_app', '0001_initial'),
        ('status_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('Open Tender', 'Open Tender'), ('Close Tender', 'Close Tender'), ('Auction', 'Auction'), ('Negotiation', 'Negotiation')], max_length=100)),
                ('delivery', models.TextField()),
                ('terms', models.DateField()),
                ('opening_date', models.DateTimeField()),
                ('closing_date', models.DateTimeField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category_app.category')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status_app.status')),
            ],
        ),
    ]
